# Generated by Django 4.2.7 on 2023-11-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistryId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('StartTimeInSeconds', models.BigIntegerField(null=True)),
                ('DurationInSeconds', models.IntegerField(null=True)),
                ('DistanceInMeters', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('Steps', models.IntegerField(null=True)),
                ('AverageSpeedInMetersPerSecond', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('AveragePaceInMinutesPerKilometer', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('TotalElevationGainInMeters', models.DecimalField(decimal_places=10, max_digits=30, null=True)),
                ('AverageHeartRateInBeatsPerMinute', models.IntegerField(null=True)),
            ],
        ),
    ]
